CREATE TABLE public.additional_services_price
(
    id                    serial4       NOT NULL,
    agreement_id          int4          NOT NULL,
    goods_type_id         int4          NOT NULL,
    additional_service_id int4          NOT NULL,
    sender_code           varchar(255)  NULL,
    sender_index_from     varchar(255)  NULL,
    sender_index_to       varchar(255)  NULL,
    sender_zone           varchar(255)  NULL,
    sender_city           varchar(255)  NULL,
    sender_region         varchar(255)  NULL,
    sender_retail         bool          NULL,
    sender_fm             bool          NULL,
    consignee_code        varchar(255)  NULL,
    consignee_index_from  varchar(255)  NULL,
    consignee_index_to    varchar(255)  NULL,
    consignee_zone        varchar(255)  NULL,
    consignee_city        varchar(255)  NULL,
    consignee_region      varchar(255)  NULL,
    consignee_retail      bool          NULL,
    consignee_fm          bool          NULL,
    unit_type             varchar(255)  NULL,
    unit_qty              numeric(8, 2) NULL,
    price                 numeric(8, 2) NULL,
    "percent"             numeric(8, 3) NULL,
    CONSTRAINT additional_services_price_pkey PRIMARY KEY (id),
    CONSTRAINT additional_services_price_additional_service_id_foreign FOREIGN KEY (additional_service_id) REFERENCES public.additional_services (id),
    CONSTRAINT additional_services_price_agreement_id_foreign FOREIGN KEY (agreement_id) REFERENCES public.agreements (id),
    CONSTRAINT additional_services_price_goods_type_id_foreign FOREIGN KEY (goods_type_id) REFERENCES public.goods_types (id)
);