spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/calculator
    username: postgres
    password: password
---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        order_inserts: true
        jdbc:
          batch_size: 50
    open-in-view: false
server:
  servlet:
    context-path: /api/v1